import './styles/styles.scss';
import './img/logo55.webp';
import './img/bsmts.webp';
import './img/video.webp';
import './img/autopilot.webp';
import './img/tahograph.webp';
import './img/podogrev.webp';
import 'bootstrap';
import '@popperjs/core';